# -*- coding: utf-8 -*-
"""pandas

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19QVT9KHTKvUw7VsCPEWJr6JtNHXdT9-n
"""

import numpy as np
import pandas as pd
#1 series
doc1={'Name':['Raju','sanju','john','piyu','preeti'],
      'Marks':[97,86,87,98,90],
      'code':[101,102,104,'null',106]}
df=pd.Series(doc1)
print(df)

#2 dataframe
df=pd.DataFrame(doc1)
print(df)

#3
doc1={'Name':['Raju','sanju','john','piyu','preeti'],
      'Marks':[97,86,87,98,90],
      'code':[101,102,104,'null',106]}

df=pd.DataFrame(doc1)
df.to_csv('file1.csv')
new_df=pd.read_csv('file1.csv')
print(new_df)

#4
p1=new_df.dropna()
print(p1)

#5
print(df.head(2))

#6
print(df.tail(2))

#7
print(df.isnull())

#8
doc1={'Name':['Raju','sanju','john','piyu','preeti'],
      'Marks':[97,86,87,98,90],
      'code':[101,102,104,'null',106]}

df=pd.DataFrame(doc1)
df.to_csv('file1.csv')
new_df=pd.read_csv('file1.csv')

x=new_df.fillna(0)
print(x)

#9
from types import new_class
x=new_df['Marks'].mean()
y=new_df.fillna(x)
print(y)

#10
print(new_df.info())

#11
print(new_df.sort_values('Marks'))

#12
x=new_df['code'].cumsum()
print(x)

#13
t=new_df['code'].median()
print(t)

#14
t=new_df['code'].mean()
print(t)

#15
u=new_df['code'].median()
new=new_df.fillna(u)
print(new)