# -*- coding: utf-8 -*-
"""Scipy

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15F9WfX-G_WP8-uQsNhK2PWmzftM1edxT
"""

from scipy import constants
print(constants.pi)

print(dir(constants))

print(constants.minute)
print(constants.hour)
print(constants.week)
print(constants.year)

import numpy as np
from scipy.fftpack import fft
x=np.array([1,2,3,4,5,6])
y=fft(x)
print(y)

from scipy.fftpack import ifft
x=np.array([1,2,3,4,5,6])
y=ifft(x)
print(y)

from scipy.fftpack import dct
x=np.array([1,2,3,4,5,6])
y=dct(x)
print(y)

from scipy.fftpack import idct
x=np.array([1,2,3,4,5,6])
y=idct(x)
print(y)

import matplotlib.pyplot as plt
from scipy import misc
face=misc.face()
plt.imshow(face)
plt.show()

face_ud=np.flipud(face)
plt.imshow(face_ud)
plt.show()

from scipy import misc,ndimage
face=misc.face()
rotate_image=ndimage.rotate(face,45)
plt.imshow(rotate_image)
plt.show()

from scipy import misc,ndimage
face=misc.face()
rotate_image=ndimage.rotate(face,-45)
plt.imshow(rotate_image)
plt.show()

from scipy import misc,ndimage
face=misc.face()
blurred_image=ndimage.gaussian_filter(face,sigma=1)
plt.imshow(blurred_image)
plt.show()

import numpy as np
from scipy.sparse import csr_matrix
arr=np.array([0,0,0,0,0,1,0,3,0,5,0,9])
print(csr_matrix(arr))

print(csr_matrix(arr).data)

print(csr_matrix(arr).count_nonzero())