# -*- coding: utf-8 -*-
"""sklearn

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1J2A73kC9h93xoVCWsL_mtyqLzW0u7Dtw
"""

#load datasets
from sklearn.datasets import load_iris
iris=load_iris()
x=iris.data
y=iris.target
feature_names=iris.feature_names
target_names=iris.target_names
print("Feature name:",feature_names)
print("target name:",target_names)
print(x[:10])

#split dataset
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris
iris=load_iris()
x=iris.data
y=iris.target
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=1)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

#Train dataset
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris
iris=load_iris()
x=iris.data
y=iris.target
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=1)

from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics

c=KNeighborsClassifier(n_neighbors=3)
c.fit(x_train,y_train)
y_pred=c.predict(x_test)
print("Accuracy:",metrics.accuracy_score(y_test,y_pred))

sample=[[1,2,3,4],[5,6,7,8]]
pred=c.predict(sample)
pred_species=[iris.target_names[p] for p in pred]
print("Prediction:",pred_species)

#preprocessing of data
import numpy as np
from sklearn import preprocessing
input_data=np.array([[1,2,3,4],[5,6,7,8],[3,4,5,6],[2,3,4,5]])
#print mean and standard deviation of data
print("Mean:",input_data.mean(axis=0))
print("std:",input_data.std(axis=0))